spring.application.name=AWS_Demo
server.port=8081
logging.file.name=/app/data/application.log
management.endpoint.health.probes.enabled=true
management.endpoints.web.base-path=/hi/actuator
management.endpoints.web.exposure.include=health
